"""Add Column

Revision ID: 8406721de091
Revises: fc2dc4d99a59
Create Date: 2026-01-27 23:14:38.466488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8406721de091'
down_revision: Union[str, Sequence[str], None] = 'fc2dc4d99a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_purchases', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premium_purchases', 'expires_at')
    # ### end Alembic commands ###
