"""Add Column

Revision ID: 87d5f6b099d0
Revises: f13818254569
Create Date: 2026-01-27 22:41:43.539099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d5f6b099d0'
down_revision: Union[str, Sequence[str], None] = 'f13818254569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_purchases', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premium_purchases', 'status')
    # ### end Alembic commands ###
